export enum AttributeType {
  ATTRSTRING = 'ATTRSTRING',

  ATTRNUMBER = 'ATTRNUMBER',

  ATTRDECIMAL = 'ATTRDECIMAL',

  ATTRSINGLESELCT = 'ATTRSINGLESELCT',

  ATTRMULTISELECT = 'ATTRMULTISELECT',

  ATTRDATE = 'ATTRDATE',

  ATTRDATETIME = 'ATTRDATETIME',

  ATTRFILEPATH = 'ATTRFILEPATH',

  ATTRIMAGEPATH = 'ATTRIMAGEPATH',
}
