export enum FieldAgentSkillRuleType {
  BRANDSKILL = 'BRANDSKILL',

  CATEGORYSKILL = 'CATEGORYSKILL',

  PINCODESKILL = 'PINCODESKILL',

  LOCATIONSKILL = 'LOCATIONSKILL',

  LANGUAGESKILL = 'LANGUAGESKILL',
}
