export enum FranchiseAllocationRuleType {
  BRANDRULE = 'BRANDRULE',

  CATEGORYRULE = 'CATEGORYRULE',

  PINCODERULE = 'PINCODERULE',

  LOCATIONRULE = 'LOCATIONRULE',

  LANGUAGERULE = 'LANGUAGERULE',
}
