export enum ServiceOrderSpareStatus {
  ADDED = 'ADDED',

  PAYMENTINIT = 'PAYMENTINIT',

  PAYMENTSUCCESS = 'PAYMENTSUCCESS',

  PAYMENTFAILED = 'PAYMENTFAILED',

  SPAREORDERED = 'SPAREORDERED',

  SPAREDELIVERED = 'SPAREDELIVERED',

  INSTALLED = 'INSTALLED',
}
