export enum ServiceOrderStatus {
  CREATED = 'CREATED',

  ASSIGNED = 'ASSIGNED',

  INPROGRESS = 'INPROGRESS',

  WAITINGFORSPARE = 'WAITINGFORSPARE',

  COMPLETED = 'COMPLETED',

  CANCELED = 'CANCELED',
}
