export enum ServiceOrderType {
  REPAIR = 'REPAIR',

  PERIODICMAINTENANCE = 'PERIODICMAINTENANCE',

  INSTALLATION = 'INSTALLATION',

  UNINSTALLATION = 'UNINSTALLATION',

  RETURNVERIFICATION = 'RETURNVERIFICATION',
}
