export enum ServiceOrderAssignmentStatus {
  ASSIGNED = 'ASSIGNED',

  MOVEDBACK = 'MOVEDBACK',

  COMPLETEDINIT = 'COMPLETEDINIT',

  COMPLETEDAPPROVED = 'COMPLETEDAPPROVED',

  CANCELATIONINIT = 'CANCELATIONINIT',

  CANCELATIONAPPROVED = 'CANCELATIONAPPROVED',
}
