package com.framasaas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FranchiseUserStatusHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseUserStatusHistoryAllPropertiesEquals(
        FranchiseUserStatusHistory expected,
        FranchiseUserStatusHistory actual
    ) {
        assertFranchiseUserStatusHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertFranchiseUserStatusHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseUserStatusHistoryAllUpdatablePropertiesEquals(
        FranchiseUserStatusHistory expected,
        FranchiseUserStatusHistory actual
    ) {
        assertFranchiseUserStatusHistoryUpdatableFieldsEquals(expected, actual);
        assertFranchiseUserStatusHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseUserStatusHistoryAutoGeneratedPropertiesEquals(
        FranchiseUserStatusHistory expected,
        FranchiseUserStatusHistory actual
    ) {
        assertThat(actual)
            .as("Verify FranchiseUserStatusHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseUserStatusHistoryUpdatableFieldsEquals(
        FranchiseUserStatusHistory expected,
        FranchiseUserStatusHistory actual
    ) {
        assertThat(actual)
            .as("Verify FranchiseUserStatusHistory relevant properties")
            .satisfies(a -> assertThat(a.getUserSatus()).as("check userSatus").isEqualTo(expected.getUserSatus()))
            .satisfies(a -> assertThat(a.getUpdatedBy()).as("check updatedBy").isEqualTo(expected.getUpdatedBy()))
            .satisfies(a -> assertThat(a.getUpdatedTime()).as("check updatedTime").isEqualTo(expected.getUpdatedTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseUserStatusHistoryUpdatableRelationshipsEquals(
        FranchiseUserStatusHistory expected,
        FranchiseUserStatusHistory actual
    ) {
        assertThat(actual)
            .as("Verify FranchiseUserStatusHistory relationships")
            .satisfies(a -> assertThat(a.getFranchiseUser()).as("check franchiseUser").isEqualTo(expected.getFranchiseUser()));
    }
}
