package com.framasaas.be.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ArticleWarrantyDetailsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleWarrantyDetailsAllPropertiesEquals(ArticleWarrantyDetails expected, ArticleWarrantyDetails actual) {
        assertArticleWarrantyDetailsAutoGeneratedPropertiesEquals(expected, actual);
        assertArticleWarrantyDetailsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleWarrantyDetailsAllUpdatablePropertiesEquals(
        ArticleWarrantyDetails expected,
        ArticleWarrantyDetails actual
    ) {
        assertArticleWarrantyDetailsUpdatableFieldsEquals(expected, actual);
        assertArticleWarrantyDetailsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleWarrantyDetailsAutoGeneratedPropertiesEquals(
        ArticleWarrantyDetails expected,
        ArticleWarrantyDetails actual
    ) {
        assertThat(actual)
            .as("Verify ArticleWarrantyDetails auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleWarrantyDetailsUpdatableFieldsEquals(ArticleWarrantyDetails expected, ArticleWarrantyDetails actual) {
        assertThat(actual)
            .as("Verify ArticleWarrantyDetails relevant properties")
            .satisfies(a -> assertThat(a.getWarrantyType()).as("check warrantyType").isEqualTo(expected.getWarrantyType()))
            .satisfies(a ->
                assertThat(a.getVendorArticleWarrantyId())
                    .as("check vendorArticleWarrantyId")
                    .isEqualTo(expected.getVendorArticleWarrantyId())
            )
            .satisfies(a ->
                assertThat(a.getVendorWarrantyMasterId()).as("check vendorWarrantyMasterId").isEqualTo(expected.getVendorWarrantyMasterId())
            )
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreateddBy()).as("check createddBy").isEqualTo(expected.getCreateddBy()))
            .satisfies(a -> assertThat(a.getCreatedTime()).as("check createdTime").isEqualTo(expected.getCreatedTime()))
            .satisfies(a -> assertThat(a.getUpdatedBy()).as("check updatedBy").isEqualTo(expected.getUpdatedBy()))
            .satisfies(a -> assertThat(a.getUpdatedTime()).as("check updatedTime").isEqualTo(expected.getUpdatedTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleWarrantyDetailsUpdatableRelationshipsEquals(
        ArticleWarrantyDetails expected,
        ArticleWarrantyDetails actual
    ) {
        assertThat(actual)
            .as("Verify ArticleWarrantyDetails relationships")
            .satisfies(a -> assertThat(a.getArticle()).as("check article").isEqualTo(expected.getArticle()))
            .satisfies(a -> assertThat(a.getWarrantyMaster()).as("check warrantyMaster").isEqualTo(expected.getWarrantyMaster()));
    }
}
