package com.framasaas.be.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FieldAgentSkillRuleSetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldAgentSkillRuleSetAllPropertiesEquals(FieldAgentSkillRuleSet expected, FieldAgentSkillRuleSet actual) {
        assertFieldAgentSkillRuleSetAutoGeneratedPropertiesEquals(expected, actual);
        assertFieldAgentSkillRuleSetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldAgentSkillRuleSetAllUpdatablePropertiesEquals(
        FieldAgentSkillRuleSet expected,
        FieldAgentSkillRuleSet actual
    ) {
        assertFieldAgentSkillRuleSetUpdatableFieldsEquals(expected, actual);
        assertFieldAgentSkillRuleSetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldAgentSkillRuleSetAutoGeneratedPropertiesEquals(
        FieldAgentSkillRuleSet expected,
        FieldAgentSkillRuleSet actual
    ) {
        assertThat(actual)
            .as("Verify FieldAgentSkillRuleSet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldAgentSkillRuleSetUpdatableFieldsEquals(FieldAgentSkillRuleSet expected, FieldAgentSkillRuleSet actual) {
        assertThat(actual)
            .as("Verify FieldAgentSkillRuleSet relevant properties")
            .satisfies(a -> assertThat(a.getSortType()).as("check sortType").isEqualTo(expected.getSortType()))
            .satisfies(a -> assertThat(a.getCreateddBy()).as("check createddBy").isEqualTo(expected.getCreateddBy()))
            .satisfies(a -> assertThat(a.getCreatedTime()).as("check createdTime").isEqualTo(expected.getCreatedTime()))
            .satisfies(a -> assertThat(a.getUpdatedBy()).as("check updatedBy").isEqualTo(expected.getUpdatedBy()))
            .satisfies(a -> assertThat(a.getUpdatedTime()).as("check updatedTime").isEqualTo(expected.getUpdatedTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldAgentSkillRuleSetUpdatableRelationshipsEquals(
        FieldAgentSkillRuleSet expected,
        FieldAgentSkillRuleSet actual
    ) {
        // empty method
    }
}
