package com.framasaas.be.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FranchiseDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseDocumentAllPropertiesEquals(FranchiseDocument expected, FranchiseDocument actual) {
        assertFranchiseDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertFranchiseDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseDocumentAllUpdatablePropertiesEquals(FranchiseDocument expected, FranchiseDocument actual) {
        assertFranchiseDocumentUpdatableFieldsEquals(expected, actual);
        assertFranchiseDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseDocumentAutoGeneratedPropertiesEquals(FranchiseDocument expected, FranchiseDocument actual) {
        assertThat(actual)
            .as("Verify FranchiseDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseDocumentUpdatableFieldsEquals(FranchiseDocument expected, FranchiseDocument actual) {
        assertThat(actual)
            .as("Verify FranchiseDocument relevant properties")
            .satisfies(a -> assertThat(a.getDocumentName()).as("check documentName").isEqualTo(expected.getDocumentName()))
            .satisfies(a -> assertThat(a.getDocumentType()).as("check documentType").isEqualTo(expected.getDocumentType()))
            .satisfies(a -> assertThat(a.getDocumentFormat()).as("check documentFormat").isEqualTo(expected.getDocumentFormat()))
            .satisfies(a -> assertThat(a.getDocumentSize()).as("check documentSize").isEqualTo(expected.getDocumentSize()))
            .satisfies(a -> assertThat(a.getDocumentPath()).as("check documentPath").isEqualTo(expected.getDocumentPath()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseDocumentUpdatableRelationshipsEquals(FranchiseDocument expected, FranchiseDocument actual) {
        assertThat(actual)
            .as("Verify FranchiseDocument relationships")
            .satisfies(a -> assertThat(a.getFranchise()).as("check franchise").isEqualTo(expected.getFranchise()));
    }
}
