package com.framasaas.be.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FranchisePerformanceHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchisePerformanceHistoryAllPropertiesEquals(
        FranchisePerformanceHistory expected,
        FranchisePerformanceHistory actual
    ) {
        assertFranchisePerformanceHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertFranchisePerformanceHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchisePerformanceHistoryAllUpdatablePropertiesEquals(
        FranchisePerformanceHistory expected,
        FranchisePerformanceHistory actual
    ) {
        assertFranchisePerformanceHistoryUpdatableFieldsEquals(expected, actual);
        assertFranchisePerformanceHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchisePerformanceHistoryAutoGeneratedPropertiesEquals(
        FranchisePerformanceHistory expected,
        FranchisePerformanceHistory actual
    ) {
        assertThat(actual)
            .as("Verify FranchisePerformanceHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchisePerformanceHistoryUpdatableFieldsEquals(
        FranchisePerformanceHistory expected,
        FranchisePerformanceHistory actual
    ) {
        assertThat(actual)
            .as("Verify FranchisePerformanceHistory relevant properties")
            .satisfies(a -> assertThat(a.getPerformanceScore()).as("check performanceScore").isEqualTo(expected.getPerformanceScore()))
            .satisfies(a -> assertThat(a.getPerformanceTag()).as("check performanceTag").isEqualTo(expected.getPerformanceTag()))
            .satisfies(a -> assertThat(a.getUpdatedBy()).as("check updatedBy").isEqualTo(expected.getUpdatedBy()))
            .satisfies(a -> assertThat(a.getUpdatedTime()).as("check updatedTime").isEqualTo(expected.getUpdatedTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchisePerformanceHistoryUpdatableRelationshipsEquals(
        FranchisePerformanceHistory expected,
        FranchisePerformanceHistory actual
    ) {
        assertThat(actual)
            .as("Verify FranchisePerformanceHistory relationships")
            .satisfies(a -> assertThat(a.getFranchise()).as("check franchise").isEqualTo(expected.getFranchise()));
    }
}
