package com.framasaas.be.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FranchiseStatusHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseStatusHistoryAllPropertiesEquals(FranchiseStatusHistory expected, FranchiseStatusHistory actual) {
        assertFranchiseStatusHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertFranchiseStatusHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseStatusHistoryAllUpdatablePropertiesEquals(
        FranchiseStatusHistory expected,
        FranchiseStatusHistory actual
    ) {
        assertFranchiseStatusHistoryUpdatableFieldsEquals(expected, actual);
        assertFranchiseStatusHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseStatusHistoryAutoGeneratedPropertiesEquals(
        FranchiseStatusHistory expected,
        FranchiseStatusHistory actual
    ) {
        assertThat(actual)
            .as("Verify FranchiseStatusHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseStatusHistoryUpdatableFieldsEquals(FranchiseStatusHistory expected, FranchiseStatusHistory actual) {
        assertThat(actual)
            .as("Verify FranchiseStatusHistory relevant properties")
            .satisfies(a -> assertThat(a.getFranchiseSatus()).as("check franchiseSatus").isEqualTo(expected.getFranchiseSatus()))
            .satisfies(a -> assertThat(a.getUpdatedBy()).as("check updatedBy").isEqualTo(expected.getUpdatedBy()))
            .satisfies(a -> assertThat(a.getUpdatedTime()).as("check updatedTime").isEqualTo(expected.getUpdatedTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFranchiseStatusHistoryUpdatableRelationshipsEquals(
        FranchiseStatusHistory expected,
        FranchiseStatusHistory actual
    ) {
        assertThat(actual)
            .as("Verify FranchiseStatusHistory relationships")
            .satisfies(a -> assertThat(a.getFranchise()).as("check franchise").isEqualTo(expected.getFranchise()));
    }
}
