package com.framasaas.be.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HsnAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHsnAllPropertiesEquals(Hsn expected, Hsn actual) {
        assertHsnAutoGeneratedPropertiesEquals(expected, actual);
        assertHsnAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHsnAllUpdatablePropertiesEquals(Hsn expected, Hsn actual) {
        assertHsnUpdatableFieldsEquals(expected, actual);
        assertHsnUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHsnAutoGeneratedPropertiesEquals(Hsn expected, Hsn actual) {
        assertThat(actual)
            .as("Verify Hsn auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHsnUpdatableFieldsEquals(Hsn expected, Hsn actual) {
        assertThat(actual)
            .as("Verify Hsn relevant properties")
            .satisfies(a -> assertThat(a.getHsnCD()).as("check hsnCD").isEqualTo(expected.getHsnCD()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getTaxRate()).as("check taxRate").isEqualTo(expected.getTaxRate()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreateddBy()).as("check createddBy").isEqualTo(expected.getCreateddBy()))
            .satisfies(a -> assertThat(a.getCreatedTime()).as("check createdTime").isEqualTo(expected.getCreatedTime()))
            .satisfies(a -> assertThat(a.getUpdatedBy()).as("check updatedBy").isEqualTo(expected.getUpdatedBy()))
            .satisfies(a -> assertThat(a.getUpdatedTime()).as("check updatedTime").isEqualTo(expected.getUpdatedTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHsnUpdatableRelationshipsEquals(Hsn expected, Hsn actual) {
        // empty method
    }
}
