package com.framasaas.be.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WarrantyMasterPriceHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarrantyMasterPriceHistoryAllPropertiesEquals(
        WarrantyMasterPriceHistory expected,
        WarrantyMasterPriceHistory actual
    ) {
        assertWarrantyMasterPriceHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertWarrantyMasterPriceHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarrantyMasterPriceHistoryAllUpdatablePropertiesEquals(
        WarrantyMasterPriceHistory expected,
        WarrantyMasterPriceHistory actual
    ) {
        assertWarrantyMasterPriceHistoryUpdatableFieldsEquals(expected, actual);
        assertWarrantyMasterPriceHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarrantyMasterPriceHistoryAutoGeneratedPropertiesEquals(
        WarrantyMasterPriceHistory expected,
        WarrantyMasterPriceHistory actual
    ) {
        assertThat(actual)
            .as("Verify WarrantyMasterPriceHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarrantyMasterPriceHistoryUpdatableFieldsEquals(
        WarrantyMasterPriceHistory expected,
        WarrantyMasterPriceHistory actual
    ) {
        assertThat(actual)
            .as("Verify WarrantyMasterPriceHistory relevant properties")
            .satisfies(a -> assertThat(a.getPrice()).as("check price").isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getTax()).as("check tax").isEqualTo(expected.getTax()))
            .satisfies(a ->
                assertThat(a.getFranchiseCommission()).as("check franchiseCommission").isEqualTo(expected.getFranchiseCommission())
            )
            .satisfies(a -> assertThat(a.getFranchiseTax()).as("check franchiseTax").isEqualTo(expected.getFranchiseTax()))
            .satisfies(a -> assertThat(a.getUpdatedBy()).as("check updatedBy").isEqualTo(expected.getUpdatedBy()))
            .satisfies(a -> assertThat(a.getUpdatedTime()).as("check updatedTime").isEqualTo(expected.getUpdatedTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarrantyMasterPriceHistoryUpdatableRelationshipsEquals(
        WarrantyMasterPriceHistory expected,
        WarrantyMasterPriceHistory actual
    ) {
        assertThat(actual)
            .as("Verify WarrantyMasterPriceHistory relationships")
            .satisfies(a -> assertThat(a.getWarrantyMaster()).as("check warrantyMaster").isEqualTo(expected.getWarrantyMaster()));
    }
}
